---
title: "Cleaning"
author: "Michael Topper"
date: "3/4/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
df = board_games <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-12/board_games.csv")

```


Exploratory Data Analysis
```{r}
df %>% ggplot(aes(average_rating)) +
  geom_histogram()


df %>% mutate(above7 = as.factor(ifelse(average_rating >= 7, 1 , 0))) %>% count(above7)

df %>% count(publisher, sort = T) 

df %>% 
  count(year_published) %>% 
  arrange(desc(year_published)) %>% 
  ggplot(aes(year_published, n)) +
  geom_line() 


df %>% filter(max_playtime < 1000) %>% ggplot(aes(max_playtime)) + 
  geom_histogram()

df %>% filter(max_playtime < 1000) %>% distinct(max_playtime) 
```

Finding the top types of games that are created. 
```{r}
catvars = df %>% 
  select(game_id, name, family, expansion, category, artist, designer, average_rating) %>% 
  gather(type, value, -game_id, -name) %>% 
  filter(!is.na(value)) %>% 
  separate_rows(value, sep = ',') %>% 
  arrange(game_id)

catcounts = catvars %>% 
  count(type, value,  sort = T)

catcounts %>% 
  filter(type == 'category') %>% 
  mutate(value = fct_reorder(value, n)) %>% 
  top_n(20, n) %>% 
  ggplot(aes(value, n)) +
  geom_col() +
  coord_flip() +
  ylab("Total") +
  xlab("Board Game Type") +
  labs(title = "Most Popular Types of Board Games")
```






Making a bar graph of decade 
```{r}
df %>% mutate(decade = 10 * (year_published %/% 10)) %>% 
  group_by(decade) %>% summarise(min_average_players = mean(min_players), avgdecaderating = mean(average_rating)) %>% 
  ggplot(aes(x = decade, y = avgdecaderating)) + 
  geom_point() + 
  geom_smooth(method = 'lm') +
  labs(title = "Average Decade Rating Over Time") +
  xlab("Decade") +
  ylab("Average Rating in the Decade") +
  theme(plot.title = element_text(hjust = 0.5)) 


```

Designers by decade.
```{r}
df %>% mutate(decade = 10 * (year_published %/% 10)) %>% 
  filter(decade > 1950) %>% 
  filter(designer != '(Uncredited)') %>% 
  group_by(decade) %>% 
  count(designer, sort = T) %>%  
  filter(!is.na(designer)) %>% 
  arrange(desc(n)) %>% 
  top_n(5, n) %>% 
  ggplot(aes(x = designer, y = n, fill = as.factor(decade) )) +
  geom_col() +
  facet_wrap(~decade) +
  coord_flip() +
  labs(fill = "Decade", title = "Top 5 Designers by Decade") +
  xlab("Designer") +
  ylab("Count")

```

