---
title: "Exploratory Analysis- Michael"
author: "Michael Topper"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(ipumsr)
######################UPLOADING DATA###############################
# NOTE: To load data, you must download both the extract's data and the DDI
# and also set the working directory to the folder with these files (or change the path below).
if (!require("ipumsr")) stop("Reading IPUMS data into R requires the ipumsr package. It can be installed using the following command: install.packages('ipumsr')")
ddi <- read_ipums_ddi("cps_00004.xml")
data <- read_ipums_micro(ddi)
```

Poking around 
```{r}
data %>% 
  View()
```


Here is the definition of all the marital statuses:
```{r}
ddi[["var_info"]][[4]][[14]]
```

Hence, 4 is our indicator for whether someone is divorced or not. Let's look at some pretty graphs.

```{r}
data %>% filter(MARST == 4) %>% 
  select(MARST, AGE, EDUC, HISPAN, ASIAN, SEX) %>% 
  View()

data %>% distinct(OCC)
data %>% filter(MARST == 4, INCTOT != 99999999) %>% 
  ggplot(aes(AGE, INCTOT)) +
  geom_point()
data %>% 
  filter(INCTOT == 99999999) %>% 
  count()
```


Changing the education variable to something we can work with. 
```{r}
new.data = data %>% 
  mutate(under.highschool = ifelse(EDUC %in% c(10,11,12,13,14,20,21,22,30,31,32,40,50,60,70,71,72), 1, 0)) %>% 
  mutate(highschool.only = ifelse(EDUC %in% c(73), 1, 0)) %>% 
  mutate(some.college = ifelse(EDUC %in% c(80,81,90,91,92,100,110),1,0)) %>% 
  mutate(bachelors = ifelse(EDUC %in% c(111), 1 , 0) ) %>% 
  mutate(graduate = ifelse(EDUC %in% c(120,121,122,123,124,125), 1 , 0)) 


new.data$education = 0
new.data$education[new.data$highschool.only == 1] = 1
new.data$education[new.data$some.college == 1] = 2
new.data$education[new.data$bachelors == 1] = 3
new.data$education[new.data$graduate == 1] = 4

new.data %>% select(education, RACE, AGE) %>% View()

```
 


